  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/app/alembic/env.py", line 99, in <module>
    run_migrations_online()
  File "/usr/app/alembic/env.py", line 93, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.11/site-packages/alembic/runtime/environment.py", line 937, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.11/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/usr/app/src/users/databases/migrations/c1bf178c6227_update_missing_unique_constraints_in_user_table.py", line 21, in upgrade
    op.create_unique_constraint('uq_phone_number_phone_code', 'user', ['phone_number', 'phone_code'])
  File "<string>", line 8, in create_unique_constraint
  File "<string>", line 3, in create_unique_constraint
  File "/usr/local/lib/python3.11/site-packages/alembic/operations/ops.py", line 479, in create_unique_constraint
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/operations/base.py", line 393, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/operations/toimpl.py", line 189, in create_constraint
    operations.impl.add_constraint(
  File "/usr/local/lib/python3.11/site-packages/alembic/ddl/impl.py", line 335, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "/usr/local/lib/python3.11/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) could not create unique index "uq_phone_number_phone_code"
DETAIL:  Key (phone_number, phone_code)=(905999999, VN) is duplicated.

[SQL: ALTER TABLE "user" ADD CONSTRAINT uq_phone_number_phone_code UNIQUE (phone_number, phone_code)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
/usr/local/lib/python3.11/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
2024-03-14 11:40:02,109 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 11:40:02,110 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 11:40:02,287 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
2024-03-14 11:40:04,111 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 11:40:04,111 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 11:40:04,170 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 11:45:00,428 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 11:45:00,428 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 11:45:00,564 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 11:45:02,431 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 11:45:02,432 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 11:45:02,503 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
2024-03-14 12:00:01,490 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:00:01,493 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 12:00:01,535 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 12:00:03,492 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:00:03,492 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 12:00:03,517 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
2024-03-14 12:20:00,992 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:20:00,994 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 12:20:01,041 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 12:20:02,994 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:20:02,995 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 12:20:03,040 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
2024-03-14 12:35:01,989 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:35:01,993 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 12:35:02,047 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
2024-03-14 12:35:03,991 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:35:03,992 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 12:35:04,022 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 12:45:00,687 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:45:00,688 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 12:45:00,731 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
2024-03-14 12:45:02,689 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 12:45:02,690 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 12:45:02,717 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 13:10:00,367 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 13:10:00,367 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:65)
2024-03-14 13:10:00,404 - log - INFO - End queue: UserTask.HANDLE_TRACKING_LAST_ACTIVE (queue_service.py:71)
2024-03-14 13:10:02,369 - log - INFO - Start run queue (queue_service.py:54)
2024-03-14 13:10:02,370 - log - INFO - Run queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:65)
2024-03-14 13:10:02,426 - log - INFO - End queue: UserTask.HANDLE_TRACKING_TOTAL_ACTIVE_TIME (queue_service.py:71)
